global:
  appName: test
  pullSecret: ghcr-login-secret

envs:
  dev:
    targetRevision: develop
  staging:
    targetRevision: main
  prod:
    targetRevision: 1.0.0

services:
  - name: example-service-1
    repository: "https://github.com/omermishania/example-service-1"
  - name: example-service-2
    repository: "https://github.com/omermishania/example-service-2"
  - name: example-service-3
    repository: "https://github.com/omermishania/example-service-3"
  - name: example-service-4
    repository: "https://github.com/omermishania/example-service-4"
