global:
  appName: another-test
  pullSecret: ghcr-login-secret
  # kafka:
  #   topics:
  #     trafficInspectionServer:
  #       incidentDiscovery:
  #         incidents:
  #           name: &traffic-inspection-server-incident-discovery-name "incidents.updated.by.id"

envs:
  dev:
    targetRevision: develop
  staging:
    targetRevision: main
  prod:
    targetRevision: 1.0.0

services:
  - name: example-service-1
    repository: "https://github.com/omermishania/example-service-1"
  - name: example-service-2
    repository: "https://github.com/omermishania/example-service-2"
  - name: example-service-3
    repository: "https://github.com/omermishania/example-service-3"
    # parameters:
    # -  topic-name: **traffic-inspection-server-incident-discovery-name
  - name: example-service-4
    repository: "https://github.com/omermishania/example-service-4"
