global:
  appName: test
  pullSecret: ghcr-login-secret
  kafka:
    topics:
      category:
        service:
            incidents:
              name: incidents.updated.by.id
            incidentsModificationRequests:
              name: incidents-modification.created.by.incident-id
            incidentsEnrichment:
              name: incidents-enrichment.updated.by.incident-id

envs:
  dev:
    targetRevision: develop
  staging:
    targetRevision: main
  prod:
    targetRevision: 1.0.0

services:
  - name: example-service-1
    repository: "https://github.com/omermishania/example-service-1"
    targetRevision: develop
  - name: example-service-2
    repository: "https://github.com/omermishania/example-service-2"
    targetRevision: develop
  - name: example-service-3
    repository: "https://github.com/omermishania/example-service-3"
    targetRevision: develop
  - name: example-service-4
    repository: "https://github.com/omermishania/example-service-4"
    targetRevision: develop
