namespace: wib-system
env: dev
destination_cluster_url: https://kubernetes.default.svc

mongodb:
  endpoint: mongo-dev.veaut.mongodb.net
  username: admin
       
services:
  - name: identity
    repository: "github.com/omermishania/identity-service"
    targetRevision: dev
    
    image: omermishania/identity-service:dev
    replicas: 2
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"


  - name: example-service-1
    repository: "github.com/omermishania/example-service-1"
    targetRevision: develop
    
    image: omermishania/identity-service:dev
    replicas: 1
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "4"
        memory: "4Gi"